### ISSUE TITLE
User Not able to signup on brave browser

### ISSUE THREAD

**Issue by Rudra-Sankha-Sinhamahapatra** [banerjeesoumya/paytm#1]
![image](https://github.com/banerjeesoumya/payzap/assets/101992909/c715d0d2-aa8a-4335-aadf-d57bf838b7ec)

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
Dont know but in chrome its working fine ,its causing problem in brave

**Comment by banerjeesoumya** [comment]
Looking into it...

**Comment by banerjeesoumya** [comment]
Fixed @Rudra-Sankha-Sinhamahapatra

**Comment by Rudra-Sankha-Sinhamahapatra** [comment]
ok
