### ISSUE TITLE
/dashboard can be hit even without authorisation

### ISSUE THREAD

**Issue by rishitkamboj** [banerjeesoumya/paytm#2]
![Screenshot (400)](https://github.com/banerjeesoumya/payzap/assets/102843851/0ef0b0ad-f2f7-4cf0-8a06-fac8cbff0a2d)

It can be accessed even without the auth and that is something that shouldnt work.

**Comment by banerjeesoumya** [comment]
Thanks..!! Looking into it...

**Comment by banerjeesoumya** [comment]
Fixed ✔️
